apiVersion: v1
kind: Service
metadata:
  labels:
    app: pymaker-web
  name: pymaker-web
spec:
  ports:
  - #name: 80-8000
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: pymaker-web
  type: ClusterIP